### ISSUE TITLE
issue if user does not have localstorage for site

### ISSUE THREAD

**Issue by mathus13** [HumanSprout/To-Do-App#2]
new sessions create an error in parsing local storage (that doesn't exist)

todos found:undefined

Uncaught SyntaxError: Unexpected token u
(anonymous function) @ todo.js:12
(anonymous function) @ todo.js:269

**Comment by HumanSprout** [comment]
Counter was saving as NAN, needed to Number() the counter from storage before evaluating, localStorage appears to be working properly now
